services:
  postgres:
    image: postgres:16
    container_name: jungleboard-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jungle
      POSTGRES_PASSWORD: jungle
      POSTGRES_DB: jungleboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
